# 프롬프트 엔지니어링
- 생성형 인공 지능(생성형 AI) 솔루션을 안내하여 원하는 결과를 생성하는 프로세스

## 참고링크
- https://platform.openai.com
- https://cookbook.openai.com/examples/how_to_format_inputs_to_chatgpt_models
- https://platform.openai.com/docs/models
- https://platform.openai.com/playground/chat?models=gpt-4o
- https://velog.io/@yule/OpenAI-API-%EB%B0%9C%EA%B8%89
- 제로샷, 원샷, 퓨샷 : https://moonlang.tistory.com/29

In [2]:
!conda install openai -y
!conda install PyMySQL -y

Channels:
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniconda/base/envs/0731

  added / updated specs:
    - openai


The following NEW packages will be INSTALLED:

  annotated-types    pkgs/main/osx-arm64::annotated-types-0.6.0-py312hca03da5_0
  distro             pkgs/main/osx-arm64::distro-1.9.0-py312hca03da5_0
  openai             pkgs/main/osx-arm64::openai-1.37.0-py312hca03da5_0
  pydantic           pkgs/main/osx-arm64::pydantic-2.5.3-py312hca03da5_0
  pydantic-core      pkgs/main/osx-arm64::pydantic-core-2.14.6-py312hf0e4da2_0
  tqdm               pkgs/main/osx-arm64::tqdm-4.66.4-py312h989b03a_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Channels:
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

OPEN AI Playground에 접속합니다.
- https://platform.openai.com/playground/chat?models=gpt-4o

In [ ]:
# You are a  very helpful code assistant.  / You are a very helpful English teacher.  / You are a  very helpful Chinese teacher.  각각 띄우고 질문.
# Tell me about GO.

In [4]:
!conda install python-dotenv -y

Channels:
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniconda/base/envs/0731

  added / updated specs:
    - python-dotenv


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-dotenv-0.21.0       |  py312hca03da5_0          38 KB
    ------------------------------------------------------------
                                           Total:          38 KB

The following NEW packages will be INSTALLED:

  click              pkgs/main/osx-arm64::click-8.1.7-py312hca03da5_0
  python-dotenv      pkgs/main/osx-arm64::python-dotenv-0.21.0-py312hca03da5_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [5]:
# OPEN AI 셋팅
import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()  # .env 파일을 읽어서 환경변수로 설정

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
client = OpenAI()

1. **client.chat.completions.create 메서드**
- OpenAI의 챗봇 모델과 대화를 나누기 위해 사용됩니다.
- 주요 파라미터:

    - model (str): 사용할 모델의 이름을 지정합니다. 예를 들어, "gpt-4", "gpt-3.5-turbo" 등
    - messages (list of dict): 모델에게 보낼 대화 메시지의 리스트입니다. 각 메시지는 다음과 같은 형식을 가집니다.
    ```
        messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "List three fruits:\n1. Apple\n2. Banana\n3."},
        {"role": "assistant", "content": "Get rid off and number."}
         ],
    ```
        - role (str): 메시지의 역할을 지정합니다. "system", "user", "assistant" 중 하나를 사용할 수 있습니다.
            - system: 채팅 AI에 지시할 내용. system의 지령은 대화의 흐름에 더 큰 영향을 줍니다.
            - user: 사용자가 작성할 메시지
            - assistant: 사용자의 응답에 따라 대답을 해주는 보조 역할입니다. 메시지는 나열된 순서대로 처리되며, assistant가 이에 대한 응답을 제공합니다.

        - content (str): 각 role에 따른 메시지의 내용입니다.
    - temperature (float, optional): 생성되는 텍스트의 창의성을 조절합니다. 값이 높을수록 더 창의적이고 예측 불가능한 결과가 나오며, 낮을수록 더 보수적이고 예측 가능한 결과가 나옵니다. 기본값은 0.7입니다.
    - max_tokens (int, optional): 생성될 응답의 최대 토큰 수를 지정합니다. 이를 통해 응답의 길이를 제한할 수 있습니다.
    - top_p (float, optional): 생성된 텍스트의 다양성을 조절하는 또 다른 방법입니다. top_p가 1이면 모든 단어를 고려하고, 0이면 가장 확률이 높은 단어만 고려합니다. top_p가 낮으면 모델이 더 정확하고 일관된 텍스트를 생성하고, 높으면 더 다양하고 창의적인 텍스트를 생성합니다. 기본값은 0.9입니다.
    - n (int, optional): 한 번의 호출로 생성할 응답의 수를 지정합니다.
    - stop (str or list of str, optional): 응답 생성을 중지할 문자열을 지정합니다. 이 문자열이 생성된 텍스트에 포함되면 그 지점에서 생성을 중단합니다.
            - 예시: ['.', '\n'] '.'을 선택하면 한 문장만 생성. \n를 누르면 한 문단만 생성 등.
    -  frequency_penalty: 생성된 토큰의 빈도에 따라 페널티를 적용하여 반복을 줄입니다. 범위는 0~2. frequency_penalty가 높으면 모델이 동일한 단어나 구문을 반복해서 사용하는 것을 억제하고, 낮으면 그대로 유지합니다. 기본값은 0입니다.
    - presence_penalty: 텍스트에 새로운 토큰이 나타날 경우 페널티를 적용합니다. 범위는 0~2.presence_penalty가 높으면 모델이 새로운 단어나 구문을 사용하는 것을 장려하고, 낮으면 그대로 유지합니다. 기본값은 0입니다.

    - 그 외

```
    logit_bias: 지정된 토큰의 발생 확률을 바이어스 값으로 수정합니다.
    logprobs: true로 설정하면 출력 토큰의 로그 확률을 반환합니다.
    top_logprobs: 각 위치에서 가장 가능성이 높은 토큰의 수를 지정합니다.
    response_format: 출력 형식을 지정합니다(예: JSON 모드).
    seed: 지정된 시드로 결정론적 샘플링을 보장합니다.
    stream: 토큰이 사용 가능해질 때마다 부분 메시지 델타를 전송합니다.
    tools: 모델이 호출할 수 있는 함수 목록을 지정합니다.
    tool_choice: 모델의 함수 호출 방식을 제어합니다(none/auto/function).
    user: 최종 사용자 모니터링 및 남용 감지를 위한 고유 식별자입니다.
```

# 제로샷, 원샷, 퓨샷 프롬프트
- 자연어 처리 모델을 학습시키거나 테스트할 때 사용하는 방식입니다.

1) 제로샷(Zero-shot) 프롬프트:
- 모델이 해당 작업에 대해 전혀 학습되지 않은 상태에서 주어진 프롬프트에 응답하는 방식입니다.

- 예시: 특정한 주제에 대해 전혀 학습되지 않은 모델에게 "이 텍스트를 요약해 주세요"라고 요청.

2) 원샷(One-shot) 프롬프트:
- 모델이 해당 작업에 대해 한 번의 예시만을 보고 주어진 프롬프트에 응답하는 방식입니다.

- 예시: 모델에게 "이 텍스트를 요약해 주세요"라는 요청과 함께 하나의 요약 예시를 제공.

3) 퓨샷(Few-shot) 프롬프트:
- 모델이 해당 작업에 대해 몇 개의 예시를 보고 주어진 프롬프트에 응답하는 방식입니다. 원샷보다 더 많은 예시를 제공하여 모델의 성능을 향상시키는 방법입니다.

- 예시: 모델에게 "이 텍스트를 요약해 주세요"라는 요청과 함께 여러 개의 요약 예시를 제공.

In [8]:
# zero shot
import openai

response =client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant. List three fruits:"}
    ],
    temperature=1,
    max_tokens=50,
    n=1,
)

print(response.choices[0].message.content)

Here are three fruits:

1. Apple
2. Banana
3. Orange

In [2]:
# one shot
import openai

response =client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant. List three fruits:"},
        {"role": "user", "content": "1. Apple\n2. Banana\n3. Orange"}
    ],
    temperature=1,
    max_tokens=50
)

print(response.choices[0].message.content)

In [3]:
# few shot
import openai

response =client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant. List three fruits:"},
        {"role": "user", "content": "1. Apple\n2. Banana\n3. Orange"},
        {"role": "user", "content": "1. mango\n2. strawberry\n3. kiwi"},
        {"role": "assistant", "content": "Get lid off the numbers"}
    ],
    temperature=1,
    max_tokens=50
)

print(response.choices[0].message.content)

# AI SQL Assistant 만들기

In [10]:
!conda install openpyxl html5lib beautifulsoup4 openai pymysql sqlalchemy -y

Channels:
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniconda/base/envs/0731

  added / updated specs:
    - beautifulsoup4
    - html5lib
    - openai
    - openpyxl
    - pymysql
    - sqlalchemy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.12.3      |  py312hca03da5_0         267 KB
    ------------------------------------------------------------
                                           Total:         267 KB

The following NEW packages will be INSTALLED:

  et_xmlfile         pkgs/main/osx-arm64::et_xmlfile-1.1.0-py312hca03da5_1
  html5lib           pkgs/main/noarch::html5lib-1.1-pyhd3eb1b0_0
  openpyxl           pkgs/main/osx-arm64::openpyxl-3.1.5-py312h80987f9_0

The following packages will be SUPERSEDED by a higher-priority channel:

  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.~ --> pkgs/main/osx-arm64::beautifulsoup4-4.12.3-py312hca03da5_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [20]:
import numpy as np
import pandas as pd
import openai
import pymysql
import sqlalchemy
# SQL DB 셋팅
from sqlalchemy import create_engine
from sqlalchemy import text # 쿼리 입력에 필요
import pymysql

# df.to_sql(name='sales_kyj', con=db)
db = create_engine(r'mysql+pymysql://fisaai:woorifisa3!W@118.67.131.22:3306/fisa?charset=utf8mb4', echo=True)
# df = pd.read_excel('AdidasSalesdata.xlsx')
db.connect()

df = pd.read_sql('select * from sales_kyj', db)
df

2024-07-31 15:23:27,730 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2024-07-31 15:23:27,731 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-31 15:23:27,745 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2024-07-31 15:23:27,745 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-31 15:23:27,753 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2024-07-31 15:23:27,753 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-31 15:23:27,776 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-31 15:23:27,777 INFO sqlalchemy.engine.Engine DESCRIBE `fisa`.`select * from sales_kyj`
2024-07-31 15:23:27,777 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-31 15:23:27,782 INFO sqlalchemy.engine.Engine select * from sales_kyj
2024-07-31 15:23:27,783 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-31 15:23:27,962 INFO sqlalchemy.engine.Engine ROLLBACK

,index,Retailer,Retailer ID,Invoice Date,Region,State,City,Gender Type,Product Category,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,0,Foot Locker,1185732,2021-10-26,Northeast,Pennsylvania,Philadelphia,Men,Apparel,55,125,68750.0,24062.50,0.35,Outlet
1,1,Foot Locker,1185732,2021-10-27,Northeast,Pennsylvania,Philadelphia,Women,Apparel,45,225,101250.0,30375.00,0.30,Outlet
2,2,Foot Locker,1185732,2021-10-28,Northeast,Pennsylvania,Philadelphia,Men,Street Footwear,45,475,213750.0,117562.50,0.55,Outlet
3,3,Foot Locker,1185732,2021-10-29,Northeast,Pennsylvania,Philadelphia,Men,Athletic Footwear,45,125,56250.0,19687.50,0.35,Outlet
4,4,Foot Locker,1185732,2021-10-30,Northeast,Pennsylvania,Philadelphia,Women,Street Footwear,35,175,61250.0,24500.00,0.40,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,9643,West Gear,1128299,2020-03-14,West,Nevada,Las Vegas,Women,Apparel,56,170,9520.0,1713.60,0.18,Outlet
9644,9644,West Gear,1128299,2020-03-15,West,Nevada,Las Vegas,Men,Street Footwear,20,149,2980.0,1192.00,0.40,Outlet
9645,9645,West Gear,1128299,2020-03-16,West,Nevada,Las Vegas,Men,Athletic Footwear,31,145,4495.0,1123.75,0.25,Outlet
9646,9646,West Gear,1128299,2020-03-17,West,Nevada,Las Vegas,Women,Street Footwear,26,128,3328.0,1397.76,0.42,Outlet
9647,9647,West Gear,1128299,2020-03-18,West,Nevada,Las Vegas,Women,Athletic Footwear,26,96,2496.0,848.64,0.34,Outlet

In [23]:
df.groupby('Region')['Total_Sales'].sum().sort_values(ascending=False)

Total_Sales column not found in the dataframe.

In [9]:
# SQL DB 셋팅
from sqlalchemy import create_engine
from sqlalchemy import text # 쿼리 입력에 필요
import pymysql

db = create_engine(r'mysql+pymysql://fisaai:woorifisa3!W@118.67.131.22:3306/fisa?charset=utf8mb4', echo=True)

In [24]:
# GPT에게 우리가 다루는 데이터, 테이블이 어떤 구조인지 알려주는 함수 작성
# 아래 테이블 구조 기준으로 코드를 작성해줄 것 요청

def table_definition_prompt(df):
    prompt = '''Given the following MYSQL Query definition,
            write queries based on the request
            \n### MySQL SQL table, with its properties:

            #
            # Sales({})
            #
            '''.format(",".join(str(x) for x in df.columns))


    return prompt

In [12]:
# 사용자로부터 어떤 것을 확인하고 싶은지 받는 내용의 함수

def prompt_input():
    nlp_text = input('궁금한 것이 무엇인가요?: ')
    return nlp_text

In [34]:
#  1. R T F C 프레임워크에 맞춰서 작성
#  Role : AI가 수행할 역할을 명확히 정의
#  Task : 수행할 구체적인 작업 기술
#  Format : 결과물의 형식과 길이를 지정
#  Constraints : 준수해야할 규칙과 제한을 명시

full_prompt = table_definition_prompt(df) + prompt_input()

# API 호출
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are an assistant that generates SQL queries based on the given MySQL table definition\
        and a natural language request. The query should start with 'SELECT' and end with a semicolon(;)."},
        {"role": "user", "content": f"A query to answer: {full_prompt}"}
    ],
    max_tokens=200, # 비용 발생하므로 시도하며 적당한 값 찾아간다. 200이면 최대 200단어까지 생성.
                    # 영어는 한 단어가 1토큰, 한글은 한 글자가 1토큰 정도
    temperature=1.0, # 창의성 발휘 여부. 0~2 사이. 0에 가까우면 strict하게, 2에 가까우면 자유롭게(창의성 필요)
    stop=None  # 특정 문자열이 들어오면 멈춘다든지. None이면 없음. .이면 문장이 끝나면 멈춘다든지
    )

In [35]:
print(response.choices[0].message.content)

SELECT Region, SUM(Total Sales) AS Total_Sales, COUNT(*) AS Number_of_Transactions
FROM Sales
GROUP BY Region;

In [40]:
def handle_response(response):
    query = response.choices[0].message.content
    query = query.strip("```").lstrip("sql\n").rstrip().replace("\n", " ")
    
    return query

In [48]:
# query validation by executing the query
def validate_query(query):
	try:
		result = db.connect().execute(text(query))
		print(result.fetchall())
	except Exception as e:
		print(e)

query = handle_response(response)
validate_query(query)

2024-07-31 15:46:12,808 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-31 15:46:12,809 INFO sqlalchemy.engine.Engine SELECT Region, SUM(Total Sales) AS Total_Sales, COUNT(*) AS Number_of_Transactions FROM Sales GROUP BY Region;
2024-07-31 15:46:12,809 INFO sqlalchemy.engine.Engine [cached since 202.2s ago] {}
(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Sales) AS Total_Sales, COUNT(*) AS Number_of_Transactions FROM Sales GROUP BY Re' at line 1")
[SQL: SELECT Region, SUM(Total Sales) AS Total_Sales, COUNT(*) AS Number_of_Transactions FROM Sales GROUP BY Region;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
# 실습
# 1. 위 함수를 정리해서 streamlit으로 변환

# 2. 해당 내용으로 데이터 분석